### ISSUE TITLE
Flushing to network

### ISSUE THREAD

**Issue by joeblew99** [oakromulo/flutter_persistent_queue#2]
I am using the analytics plugin.
I can't work out how to control the flushing to a server. Should I do it here or in the analytics plugin.

My plane it to send the data to a golang server and index it so it's possible to track usage patterns.

**Comment by oakromulo** [comment]
@joeblew99 you can do it all under `flutter_analytics`, this one is just for the local buffering - when it fills up (or any other trigger condition) it's in charge of calling the callback received from analytics and ship the local batched data to a remote destination
